name: Ruscord Node.js CI Linux Build

on:
  workflow_dispatch:

jobs:
  build-debian-x64:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    permissions:
      contents: read

    steps:
      - name: Установка зависимостей
        run: |
          apt-get update
          apt-get install -y curl git ca-certificates binutils sudo rpm libarchive-tools
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка npm-зависимостей
        run: |
          npm install -g npm@11
          if [ -f package-lock.json ]; then
            echo "Используем npm ci"
            npm ci
          else
            echo "package-lock.json не найден, запускаем npm install"
            npm install
          fi

      - name: Сборка
        run: npx electron-builder --linux --x64 --publish=never

      - name: Загрузка артефактов (.deb)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-deb
          path: dist/*.deb

      - name: Загрузка артефактов (.rpm)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-rpm
          path: dist/*.rpm

      - name: Загрузка артефактов (.tar.xz)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-tarxz
          path: dist/*.tar.xz

      - name: Загрузка артефактов (.snap)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-snap
          path: dist/*.snap

      - name: Загрузка артефактов (.AppImage)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-appimage
          path: dist/*.AppImage

      - name: Загрузка артефактов (.pacman)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-pacman
          path: dist/*.pacman

  build-debian-x32:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    permissions:
      contents: read

    steps:
      - name: Установка зависимостей и добавление архитектуры i386
        run: |
          dpkg --add-architecture i386
          apt-get update
          apt-get install -y curl git ca-certificates binutils sudo rpm libarchive-tools libc6:i386 libstdc++6:i386
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка npm-зависимостей
        run: |
          npm install -g npm@11
          if [ -f package-lock.json ]; then
            echo "Используем npm ci"
            npm ci
          else
            echo "package-lock.json не найден, запускаем npm install"
            npm install
          fi

      - name: Очистка папки dist перед сборкой
        run: rm -rf dist/*

      - name: Сборка
        run: npx electron-builder --linux --ia32 --publish=never

      - name: Загрузка артефактов (.deb)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-deb
          path: dist/*.deb

      - name: Загрузка артефактов (.rpm)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-rpm
          path: dist/*.rpm

      - name: Загрузка артефактов (.tar.xz)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-tarxz
          path: dist/*.tar.xz

      - name: Загрузка артефактов (.snap)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-snap
          path: dist/*.snap

      - name: Загрузка артефактов (.AppImage)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-appimage
          path: dist/*.AppImage

      - name: Загрузка артефактов (.pacman)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-pacman
          path: dist/*.pacman
          
